### ISSUE TITLE
author page - create logic which will check if guy is already saved

### ISSUE THREAD

**Issue by shootermv** [shootermv/follow-favorite-repos#1]
if guy is already saved - the "save" button should be disabled

**Comment by stefanuslim** [comment]
Hi, can I work on this?

**Comment by shootermv** [comment]
Yes, will be glad!

בתאריך יום ב׳, 14 בספט׳ 2020, 15:44, מאת stefanuslim ‏<
notifications@github.com>:

**Comment by stefanuslim** [comment]
> Yes, you wellcome!

sorry couldn't find your public folder

**Comment by shootermv** [comment]
Thanks, i commented it by mistake at .gitignore file... Now changed it to standard .gitignoe file. Thank you. You already did a contribution! Will be glad for more! Let me know if you have  any problems
